cjoc:
    image: cloudbees/jenkins-operations-center:1.625.3.1
    container_name: cjoc
cje1:
    image: cloudbees/jenkins-enterprise:1.625.3.1
    container_name: cje1
    environment:
        JENKINS_OPTS: --prefix=/cje1
proxy:
    image: kmadel/haproxy:cjp-trial
    ports:
        - "80:80"
        - "9000:9000"
        - "50000:50000"
